# Trigger : Quand je push sur la branche "main"
on :
  push:
    branches:
      - main
#  pull_request:
#    branches: 
#      - main
#  schedule:
#    - cron: 00 09 * * *
    
jobs:
  demo: 
    name: Demonstration d'une CI avec GitHubAction
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
      - run: ls -a
      - name: Récupérer le code
        uses: actions/checkout@v3
      - run: ls -a
# tache en sequence
#  other:
#    needs: [demo]
