# Trigger : Quand je push sur la branche "main"
on :
  push:
    branches:
      - main
#  pull_request:
#    branches: 
#      - main
#  schedule:
#    - cron: 00 09 * * *
    
jobs:
  demo: 
    name: Demonstration d'une CI avec GitHubAction
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
      - run: ls -a
      - name: Récupérer le code
        uses: actions/checkout@v3
      - run: ls -a
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package  
  build:
    needs: demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # ref_name prend le numero de version avec la mise en place d'un tag V1
      # ref_name prend le nom de la branche (ex main) s'il n'y a pas de tag
      - run: echo ${{github.ref_name}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculator:${{github.ref_name}}
                   
# tache en sequence
#  other:
#    needs: [demo]
