# Trigger : Quand je push sur la branche "main"
on :
  push:
    branches:
      - main
#  pull_request:
#    branches: 
#      - main
#  schedule:
#    - cron: 00 09 * * *
    
jobs:
  demo: 
    name: Demonstration d'une CI avec GitHubAction
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
      - run: ls -a
      - name: Récupérer le code
        uses: actions/checkout@v3
      - run: ls -a
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package  
                   
# tache en sequence
#  other:
#    needs: [demo]
